### PR TITLE
Fix compatibility issue with relx 4.0.0

### LINKED ISSUE #62: Erlang VM exited when using -internal_epmd and rebar 3.14
When deploying a GRiSP application with rebar 3.14 the OTP patch to add the `-internal_epmd` flag (i.e. https://github.com/grisp/otp/commit/5ebbd6a8f166155e32baf64cd68ee781c88e4e83) gets lost in the build process. 

When starting GRiSP using internal epmd (e.g. when having wifi configurations as described in the [wiki](https://github.com/grisp/grisp/wiki/Connecting-over-WiFI)) it results in

```
Protocol 'inet_tcp': register/listen error: econnrefused
Erlang VM exited
```

### PR DESCRIPTION
**Pull request by maehjam**
This fixes #62 .

### CODE REVIEW

**Review by eproxus — APPROVED** [review]

**Review by eproxus — CHANGES_REQUESTED** [review]
Which of the flags implied by minimal mode is actually needed? (https://www.rebar3.org/docs/deployment/releases/#modes)

**Comment by maehjam** [comment]
I would say the `{include_erts, false}` flag. I tried it out and the `{include_erts, false}` flag in rebar 3.14 doesn't prevent rebar to use the kernel installed on the system instead of our own. With `{mode, minimal}` it uses the kernel from our OTP.

**Comment by maehjam** [comment]
To be more precise: It's the `include_erts` flag that behaves different with rebar 3.14 and what we need is that the minimal mode additionally drops the system libs.

**Comment by maehjam** [comment]
Looks like I was using rebar 3.13 and not 3.14 as I thought. Hence, this fixes nothing.

**Pull request closed without merging**
